sim_data_dir: "/Users/jiguangli/bayesian-cat/data/sim_data"
cat_cog_data_dir: "/Users/jiguangli/bayesian-cat/data/cat_cog"
dese_data_dir: "/Users/jiguangli/bayesian-cat/data/DESE_data/sample_processed/2022"
nn_training_data_dir: "/Users/jiguangli/bayesian-cat/data/nn_training_data"
sim_models_dir: "/Users/jiguangli/bayesian-cat/models/sim_models"
policy_models_dir: "/Users/jiguangli/bayesian-cat/models/policy_models"
policy_nn_models_dir: "/Users/jiguangli/bayesian-cat/models/policy_nn"
q_learning_models_dir: "/Users/jiguangli/bayesian-cat/models/q_learning"
cat_cog_models_dir: "/Users/jiguangli/bayesian-cat/models/cat_cog_models"
mcmc_models_dir: "/Users/jiguangli/bayesian-cat/models/mcmc_models"
dese_models_dir: "/Users/jiguangli/bayesian-cat/models/dese"